spring.application.name=demo
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Test;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.main.allow-bean-definition-overriding=true

application.security.jwt.secret-key=025de01310deb4a531153a6dc7d66870929c859e8b248353c275d2e2bc916c63=
application.security.jwt.expiration=604800000

